version: "3"

services:
  app:
    build: .
    command: "go run main.go domain.go service.go"
    ports:
          - "8080:8080"
    environment:
         - AWS_REGION=ap-northeast-1
         - AWS_BUCKET=minin-image
         - PORT=8080